In [1]:
import pandas as pd
import numpy as np

In [2]:
data_path = '/Users/patrickokwir/Desktop/Git_Projects/National-Collision-Database-Analysis/dataset/y_2017_en.xlsx'

In [3]:
df = pd.read_excel(data_path)
df.head()

C_YEAR C_MNTH C_WDAY C_HOUR  C_SEV C_VEHS C_CONF C_RCFG C_WTHR C_RSUR  ...  \
0    2017      1      1     10      2      1      2      3      1      3  ...   
1    2017      1      1     12      2      1      4     UU      1      5  ...   
2    2017      1      1      0      2      1      3     UU      7      3  ...   
3    2017      1      1     17      2      2     21     UU      1      1  ...   
4    2017      1      1     17      2      2     21     UU      1      1  ...   

  V_TYPE V_YEAR P_ID P_SEX P_AGE P_PSN P_ISEV P_SAFE P_USER   C_CASE  
0      1   UUUU    1     M    75    11      2     NN      1  2456013  
1      1   UUUU    1     F    21    11      2      2      1  2456022  
2      1   UUUU    1     F    34    11      2      2      1  2456061  
3      1   UUUU    1     F    50    11      2      2      1  2456167  
4      1   UUUU    1     M    63    11      1     NN      1  2456167  

[5 rows x 23 columns]

Data Profiling Exploration

In [4]:
# describe the data set
df.describe()

C_YEAR          C_SEV        C_CASE
count  289823.0  289823.000000  2.898230e+05
mean     2017.0       1.984528  2.512741e+06
std         0.0       0.123419  3.293930e+04
min      2017.0       1.000000  2.455891e+06
25%      2017.0       2.000000  2.484745e+06
50%      2017.0       2.000000  2.512108e+06
75%      2017.0       2.000000  2.541550e+06
max      2017.0       2.000000  2.570302e+06

In [6]:
# check data type for each column
df.dtypes

C_YEAR     int64
C_MNTH    object
C_WDAY    object
C_HOUR    object
C_SEV      int64
C_VEHS    object
C_CONF    object
C_RCFG    object
C_WTHR    object
C_RSUR    object
C_RALN    object
C_TRAF    object
V_ID      object
V_TYPE    object
V_YEAR    object
P_ID      object
P_SEX     object
P_AGE     object
P_PSN     object
P_ISEV    object
P_SAFE    object
P_USER    object
C_CASE     int64
dtype: object

In [10]:
# print unique values in a column
for col in df.columns:
    print (col, df[col].unique())

C_YEAR [2017]
C_MNTH [1 2 3 4 5 6 7 8 9 10 11 12 'UU']
C_WDAY [1 2 3 4 5 6 7 'U']
C_HOUR [10 12 0 17 22 16 13 18 20 19 7 6 21 8 15 14 2 9 3 'UU' 11 5 23 4 1]
C_SEV [2 1]
C_VEHS [1 2 3 4 6 5 10 17 7 8 9 12 13 14 37 11 'UU' 15]
C_CONF [2 4 3 21 35 'QQ' 31 23 24 22 1 33 41 32 34 6 36 'UU' 25 5]
C_RCFG [3 'UU' 5 2 1 8 4 'QQ' 6 10 9 7]
C_WTHR [1 7 4 2 6 5 3 'U' 'Q']
C_RSUR [3 5 1 2 4 'U' 6 'Q' 9 7 8]
C_RALN [2 1 4 3 6 5 'Q' 'U']
C_TRAF [18 'UU' 16 3 1 12 6 'QQ' 5 2 13 4 15 8 9 17 10 11 7]
V_ID [1 2 99 3 4 5 6 7 8 9 11 10 12 13 14 15 16 17 18 'UU' 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37]
V_TYPE [1 20 5 'NN' 7 8 6 17 11 9 'UU' 'QQ' 19 22 18 14 16 10 23 21]
V_YEAR ['UUUU' 2001 2016 2012 2009 2008 2005 2011 2006 2007 2004 'NNNN' 2003 2015
 2010 2013 2014 2002 1998 1992 1996 2000 1997 2017 1999 1990 1993 1989
 1995 1994 1986 1988 1980 1991 1987 1985 1981 1978 1983 1973 1982 1972
 1977 1984 1975 1969 2018 1979 1970 1964 1962 1976 1974 1966 1957 1956
 1967 1968 1965 1937 1928 197

In [11]:
# return rows where C_MNTH = U
df[df['C_MNTH'] == 'UU']

C_YEAR C_MNTH C_WDAY C_HOUR  C_SEV C_VEHS C_CONF C_RCFG C_WTHR C_RSUR  \
289801    2017     UU      U     UU      2     UU     UU      1      U      U   
289802    2017     UU      U     UU      2     UU     UU      1      U      U   
289803    2017     UU      U     UU      2     UU     UU      1      U      U   
289804    2017     UU      U     UU      2     UU     UU      1      U      U   
289805    2017     UU      U     UU      2     UU     UU      1      U      U   
289806    2017     UU      U     UU      2     UU     UU      1      U      U   
289807    2017     UU      U     UU      2     UU     UU      1      U      U   
289808    2017     UU      U     UU      2     UU     UU      1      U      U   
289809    2017     UU      U     UU      2     UU     UU      1      U      U   
289810    2017     UU      U     UU      2     UU     UU      1      U      U   
289811    2017     UU      U     UU      2     UU     UU      1      U      U   
289812    2017     UU      U     UU      2     UU     UU      1      U      U   
289813    2017     UU      U     UU      2     UU     UU      1      U      U   
289814    2017     UU      U     UU      2     UU     UU      1      U      U   
289815    2017     UU      U     UU      2     UU     UU      1      U      U   
289816    2017     UU      U     UU      2     UU     UU      1      U      U   
289817    2017     UU      U     UU      2     UU     UU      1      U      U   
289818    2017     UU      U     UU      2     UU     UU      1      U      U   
289819    2017     UU      U     UU      2     UU     UU      1      U      U   
289820    2017     UU      U     UU      2     UU     UU      1      U      U   
289821    2017     UU      U     23      2      1      3      1      1      1   
289822    2017     UU      U     23      2      1      3      1      1      1   

        ... V_TYPE V_YEAR P_ID P_SEX P_AGE P_PSN P_ISEV P_SAFE P_USER   C_CASE  
289801  ...      1   UUUU    1     F    82    11      1     NN      1  2455891  
289802  ...      1   UUUU    1     M    65    11      1     NN      1  2455891  
289803  ...     NN   2000    1     N    NN    NN      N     NN      U  2455891  
289804  ...     NN   2000    2     N    NN    NN      N     NN      U  2455891  
289805  ...     NN   2000    3     N    NN    NN      N     NN      U  2455891  
289806  ...     NN   2000    4     N    NN    NN      N     NN      U  2455891  
289807  ...     NN   2000    5     N    NN    NN      N     NN      U  2455891  
289808  ...     NN   2000    6     N    NN    NN      N     NN      U  2455891  
289809  ...     NN   2000    7     N    NN    NN      N     NN      U  2455891  
289810  ...     NN   NNNN    1     M    60    11      2     UU      U  2455891  
289811  ...     NN   NNNN    2     M    31    23      2     UU      U  2455891  
289812  ...      1   UUUU   NN     N    NN    NN      N     NN      U  2455891  
289813  ...      1   UUUU    1     M    21    11      1     NN      1  2455891  
289814  ...      1   UUUU    1     M    72    11      1     NN      1  2455891  
289815  ...      1   UUUU    1     M    61    11      1     NN      1  2455891  
289816  ...      1   UUUU    1     M    38    11      1     NN      1  2455891  
289817  ...      1   UUUU    1     F    79    11      1     NN      1  2455891  
289818  ...      1   UUUU    1     F    20    11      1     NN      1  2455891  
289819  ...      1   UUUU    1     F    47    11      1     NN      1  2455891  
289820  ...      7   UUUU    1     M    24    11      1     NN      1  2455891  
289821  ...     16   UUUU    1     M    45    96      2      9      U  2570300  
289822  ...     16   UUUU    2     F    45    96      2      9      U  2570300  

[22 rows x 23 columns]

In [14]:
# check for incomplete data
df.isnull().any(axis=1).sum()

0

In [22]:
#check for default values (duplicate C_CASE)
df['C_CASE'].value_counts().sort_values().tail(60)

2502388    16
2541065    16
2498069    16
2551732    16
2458403    16
2558716    17
2505359    17
2456257    17
2477186    17
2499274    17
2554298    17
2499126    18
2538857    18
2501442    18
2472638    18
2525931    18
2481977    18
2526783    18
2514413    19
2510672    19
2551545    19
2504547    19
2499714    19
2538834    20
2455891    20
2483766    20
2523209    20
2477984    20
2550831    20
2479033    21
2543397    21
2484842    22
2471767    22
2522870    22
2521589    22
2497212    23
2459636    23
2551106    23
2514153    23
2458328    24
2478530    25
2505986    26
2484393    27
2544489    28
2544973    29
2553187    30
2539789    31
2550653    32
2526829    32
2479230    32
2506019    32
2473906    33
2538849    37
2468011    38
2500819    41
2479379    41
2501513    42
2481325    42
2483410    46
2504111    53
Name: C_CASE, dtype: int64

In [20]:
df[df['C_CASE'] == 2544489]

C_YEAR C_MNTH C_WDAY C_HOUR  C_SEV C_VEHS C_CONF C_RCFG C_WTHR C_RSUR  \
96269    2017      5      4     15      2      2     35      2      1      1   
96270    2017      5      4     15      2      2     35      2      1      1   
96271    2017      5      4     15      2      2     35      2      1      1   
96272    2017      5      4     15      2      2     35      2      1      1   
96273    2017      5      4     15      2      2     35      2      1      1   
96274    2017      5      4     15      2      2     35      2      1      1   
96275    2017      5      4     15      2      2     35      2      1      1   
96276    2017      5      4     15      2      2     35      2      1      1   
96277    2017      5      4     15      2      2     35      2      1      1   
96278    2017      5      4     15      2      2     35      2      1      1   
96279    2017      5      4     15      2      2     35      2      1      1   
96280    2017      5      4     15      2      2     35      2      1      1   
96281    2017      5      4     15      2      2     35      2      1      1   
96282    2017      5      4     15      2      2     35      2      1      1   
96283    2017      5      4     15      2      2     35      2      1      1   
96284    2017      5      4     15      2      2     35      2      1      1   
96285    2017      5      4     15      2      2     35      2      1      1   
96286    2017      5      4     15      2      2     35      2      1      1   
96287    2017      5      4     15      2      2     35      2      1      1   
96288    2017      5      4     15      2      2     35      2      1      1   
96289    2017      5      4     15      2      2     35      2      1      1   
96290    2017      5      4     15      2      2     35      2      1      1   
96291    2017      5      4     15      2      2     35      2      1      1   
96292    2017      5      4     15      2      2     35      2      1      1   
96293    2017      5      4     15      2      2     35      2      1      1   
96294    2017      5      4     15      2      2     35      2      1      1   
96295    2017      5      4     15      2      2     35      2      1      1   
96296    2017      5      4     15      2      2     35      2      1      1   

       ... V_TYPE V_YEAR P_ID P_SEX P_AGE P_PSN P_ISEV P_SAFE P_USER   C_CASE  
96269  ...      9   2014    1     M    42    11      1      2      1  2544489  
96270  ...      9   2014    2     U    UU    96      1      1      2  2544489  
96271  ...      9   2014    3     U    UU    96      1      1      2  2544489  
96272  ...      9   2014    4     U    UU    96      1      1      2  2544489  
96273  ...      9   2014    5     U    UU    96      1      1      2  2544489  
96274  ...      9   2014    6     U    UU    96      1      1      2  2544489  
96275  ...      9   2014    7     U    UU    96      1      1      2  2544489  
96276  ...      9   2014    8     U    UU    96      1      1      2  2544489  
96277  ...      9   2014    9     U    UU    96      1      1      2  2544489  
96278  ...      9   2014   10     U    UU    96      1      1      2  2544489  
96279  ...      9   2014   11     U    UU    96      1      1      2  2544489  
96280  ...      9   2014   12     U    UU    96      1      1      2  2544489  
96281  ...      9   2014   13     U    UU    96      1      1      2  2544489  
96282  ...      9   2014   14     U    UU    96      1      1      2  2544489  
96283  ...      9   2014   15     U    UU    96      1      1      2  2544489  
96284  ...      9   2014   16     U    UU    96      1      1      2  2544489  
96285  ...      9   2014   17     U    UU    96      1      1      2  2544489  
96286  ...      9   2014   18     U    UU    96      1      1      2  2544489  
96287  ...      9   2014   19     U    UU    96      1      1      2  2544489  
96288  ...      9   2014   20     U    UU    96      1      1      2  2544489  
96289 

Todo:
- Completeness
- Validity
- Uniqueness
- Consistency
- Timeliness


1. Completeness: Completeness measures the degree to which all expected records in a dataset
are present. At a data element level, completeness is the degree to which all
records have data populated when expected. At a record level, completeness is the
degree to which all data elements have data populated when expected.
- check for missing records
- check for missing data elements. 

In [26]:
# decode data using data_dict dictionary
# for each column, use column name to look lookup key in data_dict and return the values in the dictionary, replace the values in the df column with the values in the dictionary
for col in df.columns:
    df[col] = df[col].map(data_dict[col])

In [27]:
df.head()

C_YEAR C_MNTH C_WDAY C_HOUR  C_SEV C_VEHS C_CONF C_RCFG C_WTHR C_RSUR  ...  \
0    2017      1      1     10      2      1      2      3      1      3  ...   
1    2017      1      1     12      2      1      4     UU      1      5  ...   
2    2017      1      1      0      2      1      3     UU      7      3  ...   
3    2017      1      1     17      2      2     21     UU      1      1  ...   
4    2017      1      1     17      2      2     21     UU      1      1  ...   

  V_TYPE V_YEAR P_ID P_SEX P_AGE P_PSN P_ISEV P_SAFE P_USER   C_CASE  
0      1   UUUU    1     M    75    11      2     NN      1  2456013  
1      1   UUUU    1     F    21    11      2      2      1  2456022  
2      1   UUUU    1     F    34    11      2      2      1  2456061  
3      1   UUUU    1     F    50    11      2      2      1  2456167  
4      1   UUUU    1     M    63    11      1     NN      1  2456167  

[5 rows x 23 columns]

In [24]:
# check for null values
df.isnull().sum().sort_values(ascending=False)

C_YEAR    0
V_ID      0
P_USER    0
P_SAFE    0
P_ISEV    0
P_PSN     0
P_AGE     0
P_SEX     0
P_ID      0
V_YEAR    0
V_TYPE    0
C_TRAF    0
C_MNTH    0
C_RALN    0
C_RSUR    0
C_WTHR    0
C_RCFG    0
C_CONF    0
C_VEHS    0
C_SEV     0
C_HOUR    0
C_WDAY    0
C_CASE    0
dtype: int64

In [28]:
import os
import pandas as pd

def replace_values_with_data_keys(df, folder_path):
    for column in df.columns:
        csv_filename = os.path.join(folder_path, f"{column}.csv")
        
        if os.path.exists(csv_filename):
            data_keys = pd.read_csv(csv_filename)
            key_to_value = dict(zip(data_keys['Code'], data_keys['Description']))
            df[column] = df[column].replace(key_to_value)
        else:
            print(f"CSV file for column '{column}' not found.")
            
    return df

In [29]:
folder = '/Users/patrickokwir/Desktop/Git_Projects/National-Collision-Database-Analysis/notebooks'

In [30]:
df = replace_values_with_data_keys(df, folder)

CSV file for column 'C_YEAR' not found.
CSV file for column 'C_HOUR' not found.
CSV file for column 'C_CASE' not found.


In [31]:
df.head()

C_YEAR C_MNTH C_WDAY C_HOUR  C_SEV C_VEHS C_CONF   C_RCFG C_WTHR C_RSUR  \
0    2017      1      1     10      2      1      2        3      1      3   
1    2017      1      1     12      2      1      4  Unknown      1      5   
2    2017      1      1      0      2      1      3  Unknown      7      3   
3    2017      1      1     17      2      2     21  Unknown      1      1   
4    2017      1      1     17      2      2     21  Unknown      1      1   

   ... V_TYPE   V_YEAR P_ID   P_SEX P_AGE P_PSN P_ISEV  \
0  ...      1  Unknown    1    Male    75    11      2   
1  ...      1  Unknown    1  Female    21    11      2   
2  ...      1  Unknown    1  Female    34    11      2   
3  ...      1  Unknown    1  Female    50    11      2   
4  ...      1  Unknown    1    Male    63    11      1   

                           P_SAFE P_USER   C_CASE  
0  Data element is not applicable      1  2456013  
1                               2      1  2456022  
2                               2      1  2456061  
3                               2      1  2456167  
4  Data element is not applicable      1  2456167  

[5 rows x 23 columns]

In [32]:
# Replace 'U' with Unknown in df
df = df.replace('U', 'Unknown')

In [34]:
# return rows where values is not "Unknown"
def filter_rows_with_unknown(df):
    unknown_rows = df[df.apply(lambda row: (row == 'Unknown').all(), axis=1)]
    return unknown_rows

In [35]:
filter_rows_with_unknown(df)

Empty DataFrame
Columns: [C_YEAR, C_MNTH, C_WDAY, C_HOUR, C_SEV, C_VEHS, C_CONF, C_RCFG, C_WTHR, C_RSUR, C_RALN, C_TRAF, V_ID, V_TYPE, V_YEAR, P_ID, P_SEX, P_AGE, P_PSN, P_ISEV, P_SAFE, P_USER, C_CASE]
Index: []

[0 rows x 23 columns]

2. Check for validity
 
Validity measures the degree to which the values in a data element are valid.

In [37]:
# Year must be 2017
# Month must be 1-12
# Wday must be 1-7
# Hour must be 0-23
# C_SEV must be 1-2


In [38]:
# check for Year
df['C_YEAR'].unique()

array([2017])

In [39]:
df['C_MNTH'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 'Unknown'], dtype=object)

In [40]:
df['C_WDAY'].unique()

array([1, 2, 3, 4, 5, 6, 7, 'Unknown'], dtype=object)

In [41]:
df['C_HOUR'].unique()

array([10, 12, 0, 17, 22, 16, 13, 18, 20, 19, 7, 6, 21, 8, 15, 14, 2, 9,
       3, 'UU', 11, 5, 23, 4, 1], dtype=object)

In [42]:
df['C_SEV'].unique()

array([2, 1])

In [49]:
# return rows where C_MNTH, C_WDAY, C_HOUR is 'Unknown'
unknown_rows = df[(df['C_MNTH'] == 'Unknown') & (df['C_WDAY'] == 'Unknown') & (df['C_HOUR'] == 'UU')]

In [50]:
unknown_rows

C_YEAR   C_MNTH   C_WDAY C_HOUR  C_SEV   C_VEHS   C_CONF C_RCFG  \
289801    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289802    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289803    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289804    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289805    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289806    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289807    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289808    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289809    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289810    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289811    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289812    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289813    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289814    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289815    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289816    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289817    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289818    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289819    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   
289820    2017  Unknown  Unknown     UU      2  Unknown  Unknown      1   

         C_WTHR   C_RSUR  ...                          V_TYPE  \
289801  Unknown  Unknown  ...                               1   
289802  Unknown  Unknown  ...                               1   
289803  Unknown  Unknown  ...  Data element is not applicable   
289804  Unknown  Unknown  ...  Data element is not applicable   
289805  Unknown  Unknown  ...  Data element is not applicable   
289806  Unknown  Unknown  ...  Data element is not applicable   
289807  Unknown  Unknown  ...  Data element is not applicable   
289808  Unknown  Unknown  ...  Data element is not applicable   
289809  Unknown  Unknown  ...  Data element is not applicable   
289810  Unknown  Unknown  ...  Data element is not applicable   
289811  Unknown  Unknown  ...  Data element is not applicable   
289812  Unknown  Unknown  ...                               1   
289813  Unknown  Unknown  ...                               1   
289814  Unknown  Unknown  ...                               1   
289815  Unknown  Unknown  ...                               1   
289816  Unknown  Unknown  ...                               1   
289817  Unknown  Unknown  ...                               1   
289818  Unknown  Unknown  ...                               1   
289819  Unknown  Unknown  ...                               1   
289820  Unknown  Unknown  ...                               7   

                                V_YEAR                            P_ID  \
289801                         Unknown                               1   
289802                         Unknown                               1   
289803                            2000                               1   
289804                            2000                               2   
289805                            2000                               3   
289806                            2000                               4   
289807                            2000                               5   
289808                            2000                               6   
289809                            2000                               7   
289810  Data element is not applicable                               1   
289811  Data element is not applicable                               2   
289812                         Unknown  Data element is not applicable   
289813                         Unknown                               1   
289814                        

3. Test for Uniqueness 

Uniqueness measures the degree to which the records in a dataset are not
duplicated.

In [51]:
# check for duplicates
df.duplicated().sum()

1

In [52]:
df = df.replace('UU', 'Unknown')

In [53]:
df.to_csv('collision_2017.csv', index=False)